server:
  hostname: 127.0.0.1
  port: 3000
services:
  database:
    type: mariadb
    host: 127.0.0.1
    port: 3306
    username: nullboot
    password: nullboooot
    database: nullboot
  minio:
    endpoint: http://127.0.0.1:9000/
    userEndpoint: http://127.0.0.1:9000/
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: nullboot-files
security:
  jwtSecret: do_NOT_leak_this!
