export * from './tutor-profile.dto';
export * from './get-tutor-profile.dto';
export * from './approve-tutor.dto';
export * from './nominate-tutor.dto';
export * from './get-tutors.dto';
export * from './get-tutor-data-show.dto';
export * from './give-award.dto';
export * from './tutor-award.dto';
export * from './get-award.dto';
